version: "3"

services:
  configured:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: configured
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: configured
    volumes:
      - ./:/var/www/html
    networks:
      - configured-network

#Docker Networks
networks:
  configured-network:
    driver: bridge